
<div class="jumbotron masthead">
    <div class="container">
        <h1>Binumi.com / Last Voices</h1>
        <p>Based on Zend Framework 1.12, Bootstrap 2.1.0, Font Awesome 2.0, HTML5 Boilerplate 3.0.</p>
        <p><a href="/index/test-page/" class="btn btn-primary btn-large">Go to Test Page</a></p>
        <ul class="masthead-links">
            <li><a href="http://twitter.github.com/bootstrap/index.html">Bootstrap Documentation</a></li>
            <li><a href="http://fortawesome.github.com/Font-Awesome/">Font Awesome Documentation</a></li>
            <li><a href="http://framework.zend.com/manual/en/manual.html">Zend Framework Documentation</a></li>
        </ul>
    </div>
</div>

<div class="container">

    <div class="marketing">

        <h1>A Simple Base Project Template</h1>
        <p class="marketing-byline">Rocks, period.</p>

        <div class="row-fluid">

            <div class="span4">
                <img src="http://farm8.staticflickr.com/7113/7698345326_7d5a743ce3.jpg">
                <h2>Chilli.</h2>
                <p>Fistful of goodness.</p>
            </div>

            <div class="span4">
                <img src="http://farm9.staticflickr.com/8145/7698344658_74fa5669ec.jpg">
                <h2>More Chilli.</h2>
                <p>Move them around.</p>
            </div>

            <div class="span4">
                <img src="http://farm9.staticflickr.com/8147/7698345936_0a16e444b5.jpg">
                <h2>We love Chilli !</h2>
                <p>Bunch them together.</p>
            </div>
        </div>

        <hr class="soften">

    </div>

</div>
